resource_env = "DEV"
ami_id = "ami-02d7fd1c2af6eead0"
instance_type = "t2.micro"
bucket_name = "terraform-module-learning-dev"
iam_user_name = "suraj"
iam_group_name= "DevOps"
policy_name = "test_policy"